# Tai Sakuma <sakuma@fnal.gov>
require 'draw_solid_methods/draw_empty_solid.rb'
require 'draw_solid_methods/draw_Torus_2pi.rb'
require 'draw_solid_methods/draw_Torus_filled.rb'
require 'draw_solid_methods/draw_Torus.rb'
require 'draw_solid_methods/draw_PseudoTrap.rb'
require 'draw_solid_methods/draw_Trd1.rb'
require 'draw_solid_methods/draw_Box.rb'
require 'draw_solid_methods/draw_Trapezoid.rb'
require 'draw_solid_methods/draw_Cylinder.rb'
require 'draw_solid_methods/draw_Tubs.rb'
require 'draw_solid_methods/draw_Polycone_2pi.rb'
require 'draw_solid_methods/draw_Polycone.rb'
require 'draw_solid_methods/draw_Cone.rb'
require 'draw_solid_methods/draw_Polyhedra_2pi.rb'
require 'draw_solid_methods/draw_Polyhedra_lt2pi.rb'
require 'draw_solid_methods/draw_Polyhedra.rb'
require 'draw_solid_methods/draw_Polyhedra_old.rb'
require 'draw_solid_methods/draw_UnionSolid.rb'
require 'draw_solid_methods/draw_SubtractionSolid.rb'

